export const jharkhandCities = [
  "Adityapur",
  "Baharagora",
  "Bokaro Steel City",
  "Chaibasa",
  "Chatra",
  "Chirkunda",
  "Daltonganj",
  "Deoghar",
  "Dhanbad",
  "Dumka",
  "Garhwa",
  "Giridih",
  "Godda",
  "Gumla",
  "Hazaribagh",
  "Jamshedpur",
  "Jamtara",
  "Jharia",
  "Jhumri Telaiya",
  "Khunti",
  "Koderma",
  "Latehar",
  "Lohardaga",
  "Madhupur",
  "Mihijam",
  "Musabani",
  "Pakur",
  "Palamu",
  "Ramgarh",
  "Ranchi",
  "Sahibganj",
  "Saraikela",
  "Simdega",
  "Tenu Dam-cum-Kathhara",
]
